import { describe, test } from "node:test";
import { expect } from "./expect.ts";
import { buildAgentGuide, formatGuideHuman } from "../src/guide.ts";
import { rejectRemovedFlags, showToAgentOutput } from "../src/agent-output.ts";
import { yamlStringify } from "../src/yaml.ts";
import { generateSkillMarkdown, skillDirs } from "../src/skill-install.ts";

describe("ap guide", () => {
  test("buildAgentGuide has required fields", () => {
    const guide = buildAgentGuide();
    expect(guide.version).toBe(2);
    expect(guide.workflow.length > 0).toBe(true);
    expect(guide.rules.never_request_secrets_in_chat).toBe(true);
    expect(guide.commands.show).toContain("ap show");
    expect(guide.paths.global_manifest).toContain("manifest.toml");
  });

  test("formatGuideHuman stays succinct", () => {
    const lines = formatGuideHuman().split("\n");
    expect(lines.length).toBeLessThan(20);
    expect(formatGuideHuman()).toContain("ap show <name> --check");
  });

  test("guide serializes to YAML without tables", () => {
    const yaml = yamlStringify(buildAgentGuide());
    expect(yaml).toContain("version: 2");
    expect(yaml).toContain("never_request_secrets_in_chat: true");
    expect(yaml.includes("| ---")).toBe(false);
  });
});

describe("ap show YAML shape", () => {
  test("includes bundles and unbundled secrets without values", () => {
    const out = showToAgentOutput({
      ready: true,
      project: "/repo",
      global_home: "/home/.config/ap",
      bundles: {
        cloudflare: {
          name: "cloudflare",
          ready: true,
          surfaced: [{ key: "CF_EMAIL", value: "user@example.com" }],
          missing: [],
          secrets_set: ["CF_KEY"],
        },
      },
      vars: [
        { key: "CF_EMAIL", scope: "global", storage: "inline", visibility: "public", status: "set", value: "user@example.com" },
        { key: "CF_KEY", scope: "global", storage: "global", visibility: "secret", status: "set", masked: true },
        { key: "OTHER_TOKEN", scope: "global", storage: "global", visibility: "secret", status: "set", value: "must-not-show" },
        { key: "MISSING_TOKEN", scope: "global", storage: "global", visibility: "secret", status: "missing", set_with: "ap set MISSING_TOKEN --global" },
      ],
    });

    expect(out.bundles!.cloudflare.secrets).toEqual(["CF_KEY"]);
    expect(out.unbundled_secrets!.OTHER_TOKEN).toEqual({ status: "set" });
    expect(out.unbundled_secrets!.MISSING_TOKEN).toEqual({
      status: "missing",
      set_with: "ap set MISSING_TOKEN --global",
    });
    expect(JSON.stringify(out).includes("must-not-show")).toBe(false);
  });

  test("includes the next action for a missing bundle secret", () => {
    const out = showToAgentOutput({
      ready: false,
      project: null,
      global_home: "/home/.config/ap",
      bundles: {
        namecheap: {
          name: "namecheap",
          ready: false,
          surfaced: [],
          secrets_set: [],
          missing: [{ key: "NC_API_KEY", set_with: "ap set NC_API_KEY --global" }],
        },
      },
    });

    expect(out.bundles!.namecheap.next).toBe("ap set NC_API_KEY --global");
    expect(out.bundles!.namecheap.missing![0]!.key).toBe("NC_API_KEY");
  });
});

describe("removed flags", () => {
  test("rejectRemovedFlags errors on --yaml and --json", () => {
    expect(() => rejectRemovedFlags(["show", "--yaml"])).toThrow("--yaml");
    expect(() => rejectRemovedFlags(["show", "--json"])).toThrow("--json");
    expect(() => rejectRemovedFlags(["show", "--human"])).not.toThrow();
    expect(() => rejectRemovedFlags(["set", "KEY", "--unset"])).toThrow("ap unset KEY");
  });
});

describe("skill install generation", () => {
  test("generated SKILL.md points at ap guide", () => {
    const md = generateSkillMarkdown();
    expect(md).toContain("ap guide");
    expect(md).toContain("generated by ap skill install");
    expect(md.includes("## Before any external")).toBe(false);
  });

  test("skillDirs covers agents, claude, and cursor", () => {
    const project = skillDirs("project", "/repo");
    expect(project.map((l) => l.target)).toEqual(["agents", "claude", "cursor"]);
    expect(project[0]!.dir).toBe("/repo/.agents/skills/ap");
    expect(project[1]!.dir).toBe("/repo/.claude/skills/ap");
    expect(project[2]!.dir).toBe("/repo/.cursor/skills/ap");

    const global = skillDirs("global");
    expect(global[0]!.dir.endsWith("/.agents/skills/ap")).toBe(true);
    expect(global[1]!.dir.endsWith("/.claude/skills/ap")).toBe(true);
    expect(global[2]!.dir.endsWith("/.cursor/skills/ap")).toBe(true);
  });
});
