import { join } from "node:path";
import { writeTextFile, ensureDir } from "./fs-helpers.ts";
import { findProjectRoot } from "./paths.ts";

export function globalSkillDir(): string {
  return join(process.env.HOME ?? "", ".cursor", "skills", "ap");
}

export function projectSkillDir(projectRoot: string): string {
  return join(projectRoot, ".cursor", "skills", "ap");
}

export function generateSkillMarkdown(): string {
  return `---
name: ap
description: Agent-portable secrets. Run \`ap guide\` before external API calls.
---

<!-- generated by ap skill install — do not edit -->

Run \`ap guide\` for workflow. Never ask user to paste secrets.
`;
}

export async function installSkill(scope: "global" | "project"): Promise<string> {
  let destDir: string;
  if (scope === "global") {
    destDir = globalSkillDir();
  } else {
    const root = await findProjectRoot() ?? process.cwd();
    destDir = projectSkillDir(root);
  }

  await ensureDir(destDir);
  const dest = join(destDir, "SKILL.md");
  await writeTextFile(dest, generateSkillMarkdown());
  return dest;
}
