import { join, relative, dirname } from "node:path";
import { realpath, symlink, unlink } from "node:fs/promises";
import { writeTextFile, ensureDir, isNotFound, pathExists } from "./fs-helpers.ts";
import { findProjectRoot } from "./paths.ts";

export type SkillTarget = "agents" | "claude" | "cursor";

export interface SkillLocation {
  target: SkillTarget;
  dir: string;
}

/** Canonical skill lives under .agents; other tool dirs symlink to it when distinct. */
export const CANONICAL_SKILL_TARGET: SkillTarget = "agents";

export function skillDirs(scope: "global" | "project", projectRoot?: string): SkillLocation[] {
  const home = process.env.HOME ?? "";
  if (scope === "global") {
    return [
      { target: "agents", dir: join(home, ".agents", "skills", "ap") },
      { target: "claude", dir: join(home, ".claude", "skills", "ap") },
      { target: "cursor", dir: join(home, ".cursor", "skills", "ap") },
    ];
  }

  const root = projectRoot ?? process.cwd();
  return [
    { target: "agents", dir: join(root, ".agents", "skills", "ap") },
    { target: "claude", dir: join(root, ".claude", "skills", "ap") },
    { target: "cursor", dir: join(root, ".cursor", "skills", "ap") },
  ];
}

export function generateSkillMarkdown(): string {
  return `---
name: ap
description: >-
  Agent-portable secrets for external API credentials. Use when calling third-party
  APIs, checking whether secrets are set, or storing keys with ap.
---

<!-- generated by ap skill install — do not edit -->

# ap

Local secrets for agents. Bundles group related creds (e.g. \`cloudflare\`, \`namecheap\`).

## Workflow

1. \`ap show <bundle> --check\` — readiness (YAML; secret values never printed)
2. If not ready → show \`missing[].ask\` + \`missing[].set_with\` (or top-level \`next\`)
3. If ready → use surfaced public vars; run external calls via \`ap run <bundle> -- <cmd>\`

## Rules

- Prefer a named bundle on \`show\` / \`run\`
- Set secrets via stdin; project scope is the default: \`echo "$KEY" | ap set KEY\`
- Use \`--global\` only when the credential is intentionally shared across repositories
- Use \`sh -c\` under \`ap run\` when the command needs \`$VAR\` expansion
- Discover templates: \`ap catalog\`
- \`ap set\` / \`ap unset\` run hook scripts from ap.toml or \`.ap/hooks/<event>\`. \`after_run\` is backgrounded after \`ap run\`.

## Commands

\`\`\`
ap show [BUNDLE] [--check] [--human]
ap catalog
ap run [BUNDLE] -- <cmd...>
echo "$KEY" | ap set KEY
ap unset KEY
ap guide [--human]
\`\`\`
`;
}

async function replaceWithFile(path: string, content: string): Promise<void> {
  try {
    await unlink(path);
  } catch (err) {
    if (!isNotFound(err)) throw err;
  }
  await writeTextFile(path, content);
}

async function realDir(dir: string): Promise<string> {
  await ensureDir(dir);
  try {
    return await realpath(dir);
  } catch {
    return dir;
  }
}

async function linkSkill(linkPath: string, canonicalPath: string): Promise<void> {
  try {
    await unlink(linkPath);
  } catch (err) {
    if (!isNotFound(err)) throw err;
  }
  const rel = relative(dirname(linkPath), canonicalPath);
  await symlink(rel, linkPath);
}

export async function installSkill(
  scope: "global" | "project",
  options?: { projectRoot?: string },
): Promise<string[]> {
  const projectRoot =
    scope === "project"
      ? (options?.projectRoot ?? (await findProjectRoot()) ?? process.cwd())
      : undefined;
  const content = generateSkillMarkdown();
  const locations = skillDirs(scope, projectRoot);
  const dests: string[] = [];

  const canonical = locations.find((l) => l.target === CANONICAL_SKILL_TARGET)!;
  const canonicalDirReal = await realDir(canonical.dir);
  const canonicalPath = join(canonical.dir, "SKILL.md");
  // Unlink first so we never write through a leftover symlink.
  await replaceWithFile(canonicalPath, content);
  dests.push(canonicalPath);

  for (const { dir, target } of locations) {
    if (target === CANONICAL_SKILL_TARGET) continue;
    const dirReal = await realDir(dir);
    // Shared skill stores (e.g. ~/.agents/skills → agent-skills) already have the file.
    if (dirReal === canonicalDirReal) {
      dests.push(`${join(dir, "SKILL.md")} (shared)`);
      continue;
    }
    const dest = join(dir, "SKILL.md");
    await linkSkill(dest, canonicalPath);
    dests.push(`${dest} → ${relative(dirname(dest), canonicalPath)}`);
  }

  return dests;
}

/** Suggest installing the global agent skill when it is missing. */
export async function checkSkillInstallTip(
  options: { env?: NodeJS.ProcessEnv; skillPath?: string } = {},
): Promise<string | null> {
  const env = options.env ?? process.env;
  const disabled = env.AP_NO_SKILL_TIP?.toLowerCase();
  if (env.CI || disabled === "1" || disabled === "true") return null;

  const canonical = skillDirs("global").find((l) => l.target === CANONICAL_SKILL_TARGET)!;
  const skillPath = options.skillPath ?? join(canonical.dir, "SKILL.md");
  if (await pathExists(skillPath)) return null;

  return "tip: run `ap skill install` so Cursor/Claude/Codex pick up the ap skill";
}
